### ISSUE TITLE
Unable to manage containers

### ISSUE THREAD

**Issue by jpatje** [mtabishk/expose-docker-api#1]
I installed and configured the Docker Mobile app and can see all my containers, volume, etc.
However when I click on one of them, there is no option to manage (stop, start, delete etc). I can only see information about the container and can't change anything.
Running the app on Android 12. (Samsung Galaxy S20FE).

**Comment by mtabishk** [comment]
In order to manage  (stop, start, delete, etc), you need to slide the list item. Watch this: https://www.youtube.com/watch?v=p9oFaAHwdEQ

**Comment by jpatje** [comment]
How could I overlook this? Sorry and thanks a lot! Nice app!

**Comment by mtabishk** [comment]
Sure
